"""create disasters

Revision ID: 8d693c8db212
Revises: 
Create Date: 2026-07-05 06:14:36.928158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d693c8db212'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('disasters', 'disaster_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('disasters', 'severity_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('disasters', 'risk_level',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('disasters', 'population_at_risk',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('disasters', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('disasters', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index(op.f('ix_disasters_created_at'), 'disasters', ['created_at'], unique=False)
    op.create_index(op.f('ix_disasters_disaster_type'), 'disasters', ['disaster_type'], unique=False)
    op.create_index(op.f('ix_disasters_id'), 'disasters', ['id'], unique=False)
    op.create_index(op.f('ix_disasters_risk_level'), 'disasters', ['risk_level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_disasters_risk_level'), table_name='disasters')
    op.drop_index(op.f('ix_disasters_id'), table_name='disasters')
    op.drop_index(op.f('ix_disasters_disaster_type'), table_name='disasters')
    op.drop_index(op.f('ix_disasters_created_at'), table_name='disasters')
    op.alter_column('disasters', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('disasters', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('disasters', 'population_at_risk',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('disasters', 'risk_level',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('disasters', 'severity_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('disasters', 'disaster_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
